processed 8 tasks

init:
A: object(103)

task 1 'publish'. lines 8-23:
created: object(105), object(106), object(107)
mutated: object(104)

task 2 'programmable'. lines 25-27:
created: object(109)
mutated: object(107), object(108)

task 3 'view-object'. lines 29-29:
Owner: Account Address ( A )
Version: 3
Contents: sui::coin::Coin<test::fake::FAKE> {id: sui::object::UID {id: sui::object::ID {bytes: fake(109)}}, balance: sui::balance::Balance<test::fake::FAKE> {value: 100u64}}

task 4 'programmable'. lines 31-33:
Error: Transaction Effects Status: Invalid command argument at 1. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 1, kind: TypeMismatch }, source: Some("Coins do not have the same type"), command: Some(1) } }

task 5 'programmable'. lines 35-36:
Error: Transaction Effects Status: Invalid command argument at 1. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 1, kind: TypeMismatch }, source: Some("Coins do not have the same type"), command: Some(0) } }

task 6 'programmable'. lines 38-40:
Error: Transaction Effects Status: Invalid command argument at 2. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 2, kind: TypeMismatch }, source: Some("Coins do not have the same type"), command: Some(1) } }

task 7 'programmable'. lines 42-45:
Error: Transaction Effects Status: Invalid command argument at 1. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 1, kind: TypeMismatch }, source: Some("Coins do not have the same type"), command: Some(2) } }
