processed 18 tasks

init:
A: object(100)

task 1 'publish'. lines 8-114:
created: object(104)
written: object(103)

task 2 'run'. lines 116-116:
created: object(106)
written: object(105)

task 3 'run'. lines 118-122:
written: object(107)
deleted: object(106)

task 4 'run'. lines 124-124:
created: object(109)
written: object(108)

task 5 'run'. lines 126-126:
created: object(111)
written: object(109), object(110)

task 6 'run'. lines 128-132:
written: object(112)
deleted: object(109), object(111)

task 7 'run'. lines 134-134:
created: object(114)
written: object(113)

task 8 'run'. lines 136-139:
Error: Transaction Effects Status: Entry Argument Type Error. Error for argument at index 0: Type mismatch.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: EntryArgumentError(EntryArgumentError { argument_idx: 0, kind: TypeMismatch }), source: Some("Expected argument of type Test::M::ObjAny<T0>, but found type Test::M::AnotherObjAny<Test::M::Any>") } }

task 9 'run'. lines 141-141:
created: object(117)
written: object(116)

task 10 'run'. lines 143-143:
created: object(119)
written: object(118)

task 11 'run'. lines 145-148:
Error: Transaction Effects Status: Entry Argument Type Error. Error for argument at index 0: Type mismatch.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: EntryArgumentError(EntryArgumentError { argument_idx: 0, kind: TypeMismatch }), source: Some("Expected argument of type Test::M::ObjAny<T0>, but found type Test::M::AnotherObjAny<Test::M::Any>") } }

task 12 'run'. lines 150-150:
created: object(122)
written: object(121)

task 13 'run'. lines 152-155:
Error: Transaction Effects Status: Entry Argument Type Error. Error for argument at index 0: Immutable and shared objects cannot be passed by-value.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: EntryArgumentError(EntryArgumentError { argument_idx: 0, kind: InvalidObjectByValue }), source: Some("Immutable and shared objects cannot be passed by-value, violation found in argument 0") } }

task 14 'run'. lines 157-157:
created: object(125)
written: object(124)

task 15 'run'. lines 159-162:
Error: The transaction inputs contain duplicates ObjectRef's

task 16 'run'. lines 164-164:
created: object(128)
written: object(127)

task 17 'run'. lines 166-166:
Error: The transaction inputs contain duplicates ObjectRef's
